
TARGET:show_pic

${TARGET}: *.o
	gcc  -I/usr/local/include/SDL2 -I/usr/local/include/ *.c -o   show_pic  -L/usr/local/lib -lSDL2 -lSDL2_image -lSDL2_ttf -ljpeg
  

clean:
	@rm -f ${TARGET} *.o






